version: "3.4"
services:
  vpn:
    container_name: vpn
    image: bubuntux/nordvpn:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    devices:
      - /dev/net/tun
    environment:
      - USER=${VPN_USER} # vpn user, defined in .env
      - PASS=${VPN_PASSWORD} # vpn password, defined in .env
      - COUNTRY=${VPN_COUNTRY} # vpn country, defined in .env
      - NETWORK=${NETWORK} # local network mask, defined in .env
      - PROTOCOL=UDP
      - CATEGORY=P2P
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - 8080:8080 # qbittorrent web UI
      - 6881:6881/udp #  bittorrent daemon
      - 6881:6881 #  bittorrent daemon

  torrent:
    image: linuxserver/qbittorrent
    container_name: torrent
    network_mode: service:vpn
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - WEBUI_PORT=8080
    volumes:
      - /${ROOT}/Downloads:/downloads
    depends_on:
      - vpn
    restart: unless-stopped



  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/Downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${CONFIG}/config/jackett:/config # config files


  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/config/radarr:/config # config files
      - ${ROOT}/movies:/movies # movies folder
      - ${ROOT}/Downloads:/downloads # download folder

  plex-server:
    container_name: plex-server
    image: linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - VERSION=docker
    network_mode: host
    volumes:
      - ${CONFIG}/config/plex/db:/config # plex database
      - ${CONFIG}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/Downloads:/data/tvshows # tvshows library
      - ${ROOT}/Downloads:/data/movies # tvshows library
